"""
BioDockify Report Generator
Creates formatted DOCX reports for research findings.
"""

from typing import Dict, Any
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH

class ReportGenerator:
    """Base class for Report Generation."""
    def create_docx(self, research_data: Dict[str, Any], filename: str) -> str:
        raise NotImplementedError

class ResearchReportGenerator(ReportGenerator):
    """Generates standard research reports."""
    
    def create_docx(self, research_data: Dict[str, Any], filename: str) -> str:
        document = Document()
        
        # Title
        title = document.add_heading(research_data.get('title', 'Research Report'), 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        
        # Abstract
        document.add_heading('Abstract', level=1)
        abstract_text = (
            "This report summarizes the findings generated by BioDockify AI. "
            "It includes entities extracted from literature, knowledge graph statistics, "
            "and potential drug repurposing candidates."
        )
        document.add_paragraph(abstract_text)
        
        # Entities Section
        document.add_heading('Extracted Entities', level=1)
        entities = research_data.get('entities', {})
        
        if entities:
            table = document.add_table(rows=1, cols=2)
            table.style = 'Table Grid'
            hdr_cells = table.rows[0].cells
            hdr_cells[0].text = 'Category'
            hdr_cells[1].text = 'Count'
            
            for category, items in entities.items():
                row_cells = table.add_row().cells
                row_cells[0].text = category.capitalize()
                row_cells[1].text = str(len(items))
                
                # List top 5 items
                p = document.add_paragraph(f"Top {category}: ", style='List Bullet')
                p.add_run(", ".join(items[:5]) + ("..." if len(items) > 5 else ""))
        else:
            document.add_paragraph("No entities found.")

        # Graph Stats Section
        document.add_heading('Knowledge Graph Statistics', level=1)
        stats = research_data.get('stats', {})
        if stats:
            for key, val in stats.items():
                document.add_paragraph(f"{key}: {val}", style='List Bullet')
        else:
            document.add_paragraph("Graph currently empty.")

        # Save
        document.save(filename)
        return filename

if __name__ == "__main__":
    # Test
    gen = ResearchReportGenerator()
    data = {
        "title": "Alzheimer's Test",
        "entities": {"drugs": ["Donepezil", "Memantine"], "genes": ["APOE4"]},
        "stats": {"Nodes": 100, "Edges": 500}
    }
    gen.create_docx(data, "test_report.docx")
    print("Report generated: test_report.docx")
