import requests
import json

def test_latex_export():
    url = "http://localhost:8000/api/publication/export/latex"
    payload = {
        "title": "Automated Research Report",
        "author": "BioDockify AI",
        "affiliation": "Virtual Lab 1",
        "abstract": "This report was auto-generated by BioDockify.",
        "content_markdown": "# Results\n\nSignificant findings include:\n- Protein X inhibition\n- **Reduced** plaque formation\n\n## Methodology\nWe used in silico docking."
    }
    
    try:
        print("Sending request to:", url)
        resp = requests.post(url, json=payload)
        resp.raise_for_status()
        
        data = resp.json()
        print("\n--- Generated LaTeX Header ---\n")
        print(data["latex_source"][:300]) # Print first 300 chars
        print("\n[SUCCESS] LaTeX generation API works.")
        
    except Exception as e:
        print(f"[FAILURE] Test failed: {e}")
        if 'resp' in locals():
            print("Response:", resp.text)

if __name__ == "__main__":
    test_latex_export()
