import { NextRequest, NextResponse } from 'next/server';
import { db } from '@/lib/db';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { taskId, template, includeSections } = body;

    if (!taskId) {
      return NextResponse.json(
        { error: 'Task ID is required' },
        { status: 400 }
      );
    }

    const session = await db.researchSession.findUnique({
      where: { id: taskId },
      include: {
        entities: true,
      },
    });

    if (!session) {
      return NextResponse.json(
        { error: 'Research session not found' },
        { status: 404 }
      );
    }

    const reportContent = generateReport(
      session,
      template || 'standard',
      includeSections || ['Abstract', 'Introduction', 'Results', 'Discussion']
    );

    const fileName = `report_${taskId}_${template || 'standard'}.txt`;

    // Store export record
    await db.export.create({
      data: {
        type: 'report',
        format: 'txt',
        fileName,
        fileSize: reportContent.length,
        filePath: `/exports/${fileName}`,
        sessionId: taskId,
      },
    });

    return NextResponse.json({
      fileName,
      format: 'txt',
      content: reportContent,
      createdAt: new Date().toISOString(),
    });
  } catch (error) {
    console.error('Error generating report:', error);
    return NextResponse.json(
      { error: 'Failed to generate report' },
      { status: 500 }
    );
  }
}

function generateReport(session: any, template: string, sections: string[]): string {
  const entitiesByType = {
    drug: session.entities.filter((e: any) => e.type === 'drug'),
    disease: session.entities.filter((e: any) => e.type === 'disease'),
    protein: session.entities.filter((e: any) => e.type === 'protein'),
  };

  let report = `BioDockify Research Report\n`;
  report += `===========================\n\n`;
  report += `Topic: ${session.topic}\n`;
  report += `Date: ${new Date().toLocaleString()}\n`;
  report += `Status: ${session.status}\n`;
  report += `Progress: ${session.progress}%\n\n`;

  if (sections.includes('Abstract')) {
    report += `ABSTRACT\n`;
    report += `========\n\n`;
    report += `This report presents the findings of research conducted on "${session.topic}". `;
    report += `The analysis identified ${session.entities.length} key entities across multiple categories, `;
    report += `including ${entitiesByType.drug.length} drugs, ${entitiesByType.disease.length} diseases, `;
    report += `and ${entitiesByType.protein.length} proteins.\n\n`;
  }

  if (sections.includes('Introduction')) {
    report += `INTRODUCTION\n`;
    report += `============\n\n`;
    report += `Research on ${session.topic} has gained significant attention in recent years. `;
    report += `This automated analysis leverages AI-powered literature mining and entity extraction `;
    report += `to provide a comprehensive overview of the current state of knowledge.\n\n`;
  }

  if (sections.includes('Results') || sections.includes('Discussion')) {
    report += `KEY FINDINGS\n`;
    report += `============\n\n`;

    if (entitiesByType.drug.length > 0) {
      report += `Drugs (${entitiesByType.drug.length}):\n`;
      entitiesByType.drug.forEach((e: any) => {
        report += `  - ${e.name} (${(e.confidence * 100).toFixed(0)}% confidence)\n`;
        if (e.description) report += `    ${e.description}\n`;
      });
      report += `\n`;
    }

    if (entitiesByType.disease.length > 0) {
      report += `Diseases (${entitiesByType.disease.length}):\n`;
      entitiesByType.disease.forEach((e: any) => {
        report += `  - ${e.name} (${(e.confidence * 100).toFixed(0)}% confidence)\n`;
        if (e.description) report += `    ${e.description}\n`;
      });
      report += `\n`;
    }

    if (entitiesByType.protein.length > 0) {
      report += `Proteins (${entitiesByType.protein.length}):\n`;
      entitiesByType.protein.forEach((e: any) => {
        report += `  - ${e.name} (${(e.confidence * 100).toFixed(0)}% confidence)\n`;
        if (e.description) report += `    ${e.description}\n`;
      });
      report += `\n`;
    }
  }

  if (sections.includes('Methodology')) {
    report += `METHODOLOGY\n`;
    report += `============\n\n`;
    report += `This report was generated using BioDockify's automated research pipeline:\n`;
    report += `1. Literature Search - Querying academic databases\n`;
    report += `2. Entity Extraction - AI-powered entity recognition\n`;
    report += `3. Knowledge Graph - Relationship mapping\n`;
    report += `4. Report Synthesis - Automated document generation\n\n`;
  }

  if (sections.includes('References')) {
    report += `REFERENCES\n`;
    report += `==========\n\n`;
    report += `[Note: Automated citation generation would be implemented here]\n\n`;
  }

  report += `---\n\n`;
  report += `Generated by BioDockify\n`;
  report += `https://biodockify.com\n`;

  return report;
}
