import os
import shutil
import json
import time
from datetime import datetime
from typing import List, Dict, Optional

# Mocking Google Drive API for local demonstration as explicit credentials 
# are not available in this environment. 
# In production, swap with `google.oauth2.credentials` and `googleapiclient.discovery`.

class DriveClient:
    def __init__(self, storage_path: str = "mock_drive_cloud"):
        self.storage_path = os.path.abspath(storage_path)
        self.authenticated = False
        self.user_email = None
        
        # Ensure mock cloud exists
        if not os.path.exists(self.storage_path):
            os.makedirs(self.storage_path)
            
        self.backup_folder_name = "AgentZero_Backup"
        self.full_backup_path = os.path.join(self.storage_path, self.backup_folder_name)
        if not os.path.exists(self.full_backup_path):
            os.makedirs(self.full_backup_path)
            os.makedirs(os.path.join(self.full_backup_path, "snapshots"))

    def get_auth_url(self) -> str:
        """
        Returns the URL for the user to sign in.
        CONSTRAINT: Must direct to www.biodockify.com
        """
        # In real OAuth, this would be generated by flow.authorization_url()
        return "https://www.biodockify.com/auth/google/authorize?client_id=agent_zero_desktop&scope=drive.file+email"

    def authenticate(self, auth_code: str) -> bool:
        """
        Simulates exchanging the auth code for a token.
        """
        if auth_code == "simulated_valid_code_123" or auth_code:
            self.authenticated = True
            # Simulate fetching user profile from Gmail scope
            self.user_email = "researcher@biodockify.com" 
            return True
        return False

    def is_connected(self) -> bool:
        return self.authenticated

    def get_user_info(self) -> Dict:
        return {
            "email": self.user_email,
            "name": "BioDockify Researcher",
            "connected": self.authenticated
        }

    def upload_snapshot(self, local_path: str, filename: str) -> str:
        """
        Uploads a file to the 'snapshots' folder in Drive.
        """
        if not self.authenticated:
            raise Exception("Not authenticated with Google Drive")

        target_path = os.path.join(self.full_backup_path, "snapshots", filename)
        shutil.copy2(local_path, target_path)
        
        # Mock metadata update
        metadata = {
            "last_backup": datetime.now().isoformat(),
            "file_id": f"gdrive_id_{int(time.time())}",
            "filename": filename
        }
        with open(os.path.join(self.full_backup_path, "metadata.json"), 'w') as f:
            json.dump(metadata, f)
            
        return metadata["file_id"]

    def list_backups(self) -> List[Dict]:
        """
        Lists available snapshots.
        """
        if not self.authenticated:
            return []
            
        snapshots_dir = os.path.join(self.full_backup_path, "snapshots")
        backups = []
        for f in os.listdir(snapshots_dir):
            path = os.path.join(snapshots_dir, f)
            backups.append({
                "id": f"id_{f}",
                "name": f,
                "created_time": datetime.fromtimestamp(os.path.getmtime(path)).isoformat(),
                "size": os.path.getsize(path)
            })
        
        # Sort by date desc
        backups.sort(key=lambda x: x['created_time'], reverse=True)
        return backups

    def download_snapshot(self, file_id: str, dest_path: str):
        """
        Downloads a snapshot by ID (simulated by name/id matching)
        """
        if not self.authenticated:
            raise Exception("Not authenticated")
            
        # In mock, we iterate to find the file since ID is fake
        snapshots_dir = os.path.join(self.full_backup_path, "snapshots")
        # Simple find logic for mock
        target_file = None
        for f in os.listdir(snapshots_dir):
            if f in file_id or f"id_{f}" == file_id:
                target_file = os.path.join(snapshots_dir, f)
                break
        
        if target_file and os.path.exists(target_file):
            shutil.copy2(target_file, dest_path)
        else:
            raise Exception("Backup not found in Cloud Storage")
